#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 8b93847
#
Name     : audacious
Version  : 4.4.2
Release  : 9
URL      : https://distfiles.audacious-media-player.org/audacious-4.4.2.tar.bz2
Source0  : https://distfiles.audacious-media-player.org/audacious-4.4.2.tar.bz2
Summary  : Audacious is a versatile and handy multi platform media player
Group    : Development/Tools
License  : BSD-3-Clause
Requires: audacious-bin = %{version}-%{release}
Requires: audacious-data = %{version}-%{release}
Requires: audacious-lib = %{version}-%{release}
Requires: audacious-license = %{version}-%{release}
Requires: audacious-locales = %{version}-%{release}
Requires: audacious-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : pkgconfig(Qt6Core)
BuildRequires : pkgconfig(Qt6Gui)
BuildRequires : pkgconfig(Qt6Svg)
BuildRequires : pkgconfig(Qt6Widgets)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : qt6tools-dev
BuildRequires : qtdeclarative-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Audacious @PACKAGE_VERSION@ for Windows
https://audacious-media-player.org
Audacious is free and open source software.  By installing Audacious, you agree
to be bound by various licenses governing its use and redistribution.

%package bin
Summary: bin components for the audacious package.
Group: Binaries
Requires: audacious-data = %{version}-%{release}
Requires: audacious-license = %{version}-%{release}

%description bin
bin components for the audacious package.


%package data
Summary: data components for the audacious package.
Group: Data

%description data
data components for the audacious package.


%package dev
Summary: dev components for the audacious package.
Group: Development
Requires: audacious-lib = %{version}-%{release}
Requires: audacious-bin = %{version}-%{release}
Requires: audacious-data = %{version}-%{release}
Provides: audacious-devel = %{version}-%{release}
Requires: audacious = %{version}-%{release}

%description dev
dev components for the audacious package.


%package lib
Summary: lib components for the audacious package.
Group: Libraries
Requires: audacious-data = %{version}-%{release}
Requires: audacious-license = %{version}-%{release}

%description lib
lib components for the audacious package.


%package license
Summary: license components for the audacious package.
Group: Default

%description license
license components for the audacious package.


%package locales
Summary: locales components for the audacious package.
Group: Default

%description locales
locales components for the audacious package.


%package man
Summary: man components for the audacious package.
Group: Default

%description man
man components for the audacious package.


%prep
%setup -q -n audacious-4.4.2
cd %{_builddir}/audacious-4.4.2

%build
## build_prepend content
PATH="/usr/lib64/qt6/bin:$PATH"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739343679
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/audacious
cp %{_builddir}/audacious-%{version}/COPYING %{buildroot}/usr/share/package-licenses/audacious/9baf845a8bfcfbf31732661e5b36d2e85e631cd6 || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang audacious

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/audacious
/usr/bin/audtool

%files data
%defattr(-,root,root,-)
/usr/share/applications/audacious.desktop
/usr/share/audacious/AUTHORS
/usr/share/audacious/COPYING
/usr/share/icons/hicolor/48x48/apps/audacious.png
/usr/share/icons/hicolor/scalable/apps/audacious.svg

%files dev
%defattr(-,root,root,-)
/usr/include/audacious/audtag.h
/usr/include/libaudcore/archive_reader.h
/usr/include/libaudcore/audio.h
/usr/include/libaudcore/audstrings.h
/usr/include/libaudcore/drct.h
/usr/include/libaudcore/equalizer.h
/usr/include/libaudcore/export.h
/usr/include/libaudcore/hook.h
/usr/include/libaudcore/i18n.h
/usr/include/libaudcore/index.h
/usr/include/libaudcore/inifile.h
/usr/include/libaudcore/interface.h
/usr/include/libaudcore/list.h
/usr/include/libaudcore/mainloop.h
/usr/include/libaudcore/multihash.h
/usr/include/libaudcore/objects.h
/usr/include/libaudcore/playlist.h
/usr/include/libaudcore/plugin.h
/usr/include/libaudcore/plugins.h
/usr/include/libaudcore/preferences.h
/usr/include/libaudcore/probe.h
/usr/include/libaudcore/ringbuf.h
/usr/include/libaudcore/runtime.h
/usr/include/libaudcore/templates.h
/usr/include/libaudcore/threads.h
/usr/include/libaudcore/tinylock.h
/usr/include/libaudcore/tuple.h
/usr/include/libaudcore/vfs.h
/usr/include/libaudcore/vfs_async.h
/usr/include/libaudcore/visualizer.h
/usr/include/libaudgui/gtk-compat.h
/usr/include/libaudgui/libaudgui-gtk.h
/usr/include/libaudgui/libaudgui.h
/usr/include/libaudgui/list.h
/usr/include/libaudgui/menu.h
/usr/include/libaudqt/colorbutton.h
/usr/include/libaudqt/dock.h
/usr/include/libaudqt/export.h
/usr/include/libaudqt/iface.h
/usr/include/libaudqt/info-widget.h
/usr/include/libaudqt/libaudqt.h
/usr/include/libaudqt/menu.h
/usr/include/libaudqt/treeview.h
/usr/lib64/libaudcore.so
/usr/lib64/libaudgui.so
/usr/lib64/libaudqt.so
/usr/lib64/libaudtag.so
/usr/lib64/pkgconfig/audacious.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libaudcore.so.5
/usr/lib64/libaudcore.so.5.5.0
/usr/lib64/libaudgui.so.6
/usr/lib64/libaudgui.so.6.0.0
/usr/lib64/libaudqt.so.3
/usr/lib64/libaudqt.so.3.0.0
/usr/lib64/libaudtag.so.3
/usr/lib64/libaudtag.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/audacious/9baf845a8bfcfbf31732661e5b36d2e85e631cd6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/audacious.1
/usr/share/man/man1/audtool.1

%files locales -f audacious.lang
%defattr(-,root,root,-)

